apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/qpowjohn/app-to-apps-chart'
    targetRevision: main
    path: app-to-apps-chart
    helm:
      valueFiles:
        - values-uat.yaml  # 使用 dev 環境的配置文件
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
